In [2]:
# All the imports
import numpy as np

In [4]:
# Examples
A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])

cal=A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [7]:
percent=(A/cal)*100
percent

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [11]:
B=np.array([[1],[2],[3],[4],[5]])
B=B+100 # Broadcasting- Python automatically converts the 100 into a vector of 4*1 and then does the addition.
B

array([[101],
       [102],
       [103],
       [104],
       [105]])

In [13]:
C=np.array([[1,2,3],[4,5,6]])
D=np.array([100,200,300])
E=C+D # Python does the broadcasting and copies the 1st row of array D into a second row and then does the addition. 
E

array([[101, 202, 303],
       [104, 205, 306]])

In [17]:
F=np.array([[1,2,3],[4,5,6]])
G=np.array([[100],[200]])
H=F+G # Same concept as above. 
H

array([[101, 102, 103],
       [204, 205, 206]])

In [31]:
a=np.random.randn(5)
print(a.shape)
print(a)
print(a.T) 
print(np.dot(a,a.T))
# We dont use structures where the shape is (n,) as it is not a column or a row vector. It is called rank 1 array.

(5,)
[ 0.20958614 -1.4075999   0.98211433  0.80529716 -0.78244057]
[ 0.20958614 -1.4075999   0.98211433  0.80529716 -0.78244057]
4.250529127413454


In [36]:
a=np.random.randn(5,1)
print(a,'\n')
print(np.dot(a,a.T))

[[-1.36363973]
 [-0.45561182]
 [-1.80818783]
 [ 0.09508785]
 [-1.62553713]] 

[[ 1.85951331  0.62129038  2.46571677 -0.12966557  2.21664701]
 [ 0.62129038  0.20758213  0.82383175 -0.04332315  0.74061393]
 [ 2.46571677  0.82383175  3.26954324 -0.17193669  2.93927646]
 [-0.12966557 -0.04332315 -0.17193669  0.0090417  -0.15456882]
 [ 2.21664701  0.74061393  2.93927646 -0.15456882  2.64237095]]


In [39]:
X=np.array([1,2,4,5,2,1,2,3,12,1,2,123,23,2,13,1,21,2])
X.shape

(18,)